<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Helldivers2ModManager.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helldivers2ModManager.Core\Helldivers2ModManager.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
    <PackageReference Include="SharpSevenZip" Version="2.0.77" />
  </ItemGroup>
</Project>
