name: Build-Test

on:
  push:
    branches:
      - Actions-Test

jobs:
    HD2MM-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Build
              run: |
                cd Helldivers2ModManager
                dotnet publish Helldivers2ModManager.csproj --configuration Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableWindowsTargeting=true -o HD2MM-Complete

            - name: Zip Build HD2MM-Complete File
              uses: vimtor/action-zip@v1.2
              with:
                files: Helldivers2ModManager/HD2MM-Complete
                dest: Helldivers2ModManager.zip

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: HD2MM-Complete
                  path: Helldivers2ModManager.zip

            - name: Upload Build HD2MM-Complete File to Release
              uses: softprops/action-gh-release@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                tag_name: ${{github.ref_name}}
                name: Releases ${{github.ref_name}}
                draft: true
                #prerelease: false
                files: Helldivers2ModManager.zip

    Purger-build:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.0.x'

          - name: Build
            run: |
              cd Purger
              dotnet publish Purger.csproj --configuration Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableWindowsTargeting=true -o Purger-Complete

          - name: Zip Build Purger-Complete File
            uses: vimtor/action-zip@v1.2
            with:
              files: Purger/Purger-Complete
              dest: Purger.zip

          - name: Upload
            uses: actions/upload-artifact@v4
            with:
                name: Purger-Complete
                path: Purger.zip

          - name: Upload Build Purger-Complete File to Release
            uses: softprops/action-gh-release@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              tag_name: ${{github.ref_name}}
              name: Releases ${{github.ref_name}}
              draft: true
              #prerelease: false
              files: Purger.zip